# Generated by Django 4.2.7 on 2023-12-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='postimage',
        ),
    ]
