# Generated by Django 4.2.6 on 2024-01-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_rename_post_post_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
